config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users  do
    get :search, on: :collection, defaults: { format: 'json' }
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :friendships, only: [:new, :create, :destroy]
  resources :messages
  resources :wall_posts do
    get :paging, on: :collection
  end
  resources :comments

  post "logout" => "sessions#destroy"
  get "users" => "users#index"
  get "settings" => "users#edit"
  post "update" => "users#update"
  delete "unfriend" => "friendships#destroy"
  get 'inbox' => 'messages#inbox'
  get 'messages/new'
  get 'sent' => 'messages#sent'
  get 'friends/new' => "users#find"
  get 'profile' => 'users#show' 
  get 'newsfeed' => 'wall_posts#index'
  post "toggle_like" => "likes#toggle"
  get 'walls/:id' => 'walls#show', as: 'wall'
  get 'search/u' => 'home#searchu'
  get 'search/p' => 'home#searchp'
end

app/models/user.rb
class User < ApplicationRecord
  validates :firstname, presence: true, length: { in: 2..20 }
  validates :lastname, presence: true, length: { in: 2..20 }
  validates :email, presence: true, uniqueness: true
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, dependent: :destroy
  has_many :received_messages, foreign_key: "recipient_id", class_name: "Message", dependent: :destroy
  has_many :sent_messages, foreign_key: "sender_id", class_name: "Message", dependent: :destroy
  has_many :wall_posts, foreign_key: "author_id", class_name: "WallPost", dependent: :destroy
  has_many :wall_mentions, foreign_key: "mention_id", class_name: "WallPost", dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :walls,  dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  
  #validates_email_format_of :email, :message => "needs to be a valid email address."
  has_secure_password

  def image_url_or_default
    avatar.url || image_url.presence || "http://lorempixel.com/128/128/people/Fake-User/"
  end

  def self.generate_users(n = 25, gender = "female")
    url = "https://randomuser.me/api?results=#{n}&gender=#{gender}"
    body = HTTP.get(url).parse
    body["results"].each do |person|
      hash = {}
      hash[:firstname] = person["name"]["first"]
      hash[:lastname] = person["name"]["last"]
      hash[:email] = person["email"]
      hash[:password] = person["login"]["password"]
      hash[:remote_avatar_url] = person["picture"]["large"]
      User.create! hash
    end
  end

  def add_friend(friend)
    friends << friend
  end

  def is_friend?(friend)
    friends.include?(friend)
  end

  def added_as_friend_count(user)
    added_list = friendships.find_by(friend_id: user.id)
    added_list.count
  end

  def recipients
    friends.map{|e| [e.fullname, e.id]}
  end

  def fullname
    fullname = firstname.titleize + " " + lastname.titleize
    fullname
  end

  def self.mentioned_name(wall_post)
    user = User.find(wall_post.mention_id)
    user.fullname
  end

  def likes_toggle!(item)
    likes.where(item: item).first ? likes.where(item: item).first.destroy : likes.create(item: item)
  end

  def self.random_user
    random_index = rand(User.count)
    User.offset(random_index).first
  end

  def posts_on_wall(user)
    WallPost.where(mention_id: user.id).or(WallPost.where(author: user))
  end

  def self.autocomplete_by_name(q)
    User.where('firstname ILIKE ?', "%#{q}%")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:index, :find, :edit, :show] 
  before_action :skip_if_logged_in, only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to newsfeed_path
    else
      flash[:error] = "Something went wrong: #{@user.errors.full_messages.to_sentence}."
      render "new"
    end
  end

  def index
    @users = User.where.not(id: current_user.id)
    
    if params[:q]
      @users = @users.select{|s| s.fullname.include?(params["q"])}
    end
  end

  def find
    @users = User.where.not(id: current_user.id)

    if params[:q]
      @users = @users.select{|s| s.fullname.include?(params["q"])}
    end
  end

  def edit
    @user = current_user
  end

  def show
    @user = current_user
    #wallposts_combo = current_user.wall_posts.all + current_user.wall_mentions.all
    @wallposts = @user.posts_on_wall(@user).order("updated_at DESC").page(1).per(5)
    @wallpost = WallPost.new
  end

  def update
    @user = current_user
    if params[:user][:image_url]
      if @user.update(image_url: params[:user][:image_url])
      flash[:success] = "Profile picture changed successfully"
      redirect_to settings_path
      else
        flash[:error] = "Something went wrong: #{@user.errors.full_messages.to_sentence}."
        redirect_to settings_path
      end
    elsif params[:user][:old_password]
      if @user.authenticate(params[:user][:old_password])
        @user.update(password: params[:user][:password], password_confirmation: params[:user][:password_confirmation])
        flash[:success] = "Password changed successfully"
        redirect_to settings_path
      else
        flash[:error] = "Incorrect password."
        redirect_to settings_path
      end
    elsif @user.update user_params
      flash[:success] = "Profile updated successfully."
      redirect_to settings_path
    else
      flash[:error] = "Something went wrong: #{@user.errors.full_messages.to_sentence}"
      redirect_to settings_path
    end
  end

  def search
    search = params[:q] || nil
    users = User.autocomplete_by_name(search)
    render json: users
  end

  private

  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :image_url, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="columns">
  <div class="column">
    <%= render 'layouts/menu' %>
  </div>
  <div class="column is-half">
   <div class="card" style="margin-top: 25px;">
      <header class="card-header">
        <p class="card-header-title">
          Edit Your Personal Information
        </p>
      </header>
      <div class="card-content">
      <%= form_for @user do |f| %>
        <div class="content">
          <div class="field">
            <div class="control">
              <%= f.text_field :firstname, placeholder: "First Name", class: "input"%>
            </div>
          </div>
          <div class="field">
              <div class="control">
              <%= f.text_field :lastname, placeholder: "Last Name", class: "input"%>
              </div>
          </div>
          <div class="field">
              <div class="control">
              <%= f.text_field :email, placeholder: "Email Address", class: "input"%>
              </div>
          </div>
            <div class="field">
              <div class="control">
                <%= f.submit "Update Info", class: "button is-info"%>
              </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <div class="card" style="margin-top: 25px;">
      <header class="card-header">
        <p class="card-header-title">
          Change Your Password
        </p>
        <a class="card-header-icon" id="password-toggle-icon">
          <span class="icon">
            <i class="fa fa-angle-down"></i>
          </span>
        </a>
      </header>
      <div class="card-content hidden" id="password-change">
      <%= form_for @user do |f| %>
        <div class="content">
          <div class="field">
              <div class="control">
              <%= f.password_field :old_password, placeholder: "Old Password", class: "input"%>
              </div>
          </div>
          <div class="field">
              <div class="control">
              <%= f.password_field :password, placeholder: "New Password", class: "input"%>
              </div>
          </div>
          <div class="field">
              <div class="control">
              <%= f.password_field :password_confirmation, placeholder: "Confirm New Password", class: "input"%>
              </div>
          </div>
            <div class="field">
              <div class="control">
                <%= f.submit "Change Password", class: "button is-info"%>
              </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="column">
  <div class="card" style="margin-top: 25px;">
      <header class="card-header">
        <p class="card-header-title">
          Change your Avatar
        </p>
      </header>
      <div class="card-content">
      <%= form_for @user do |f| %>
        <div class="content">
          <div class="media-content">
            <figure class="image is-96x96">
              <img src="<%= @user.avatar %>" alt="Image" style="border-radius: 50%;">
            </figure>
          </div>
          <div class="field">
              <div class="control">
              <%= f.file_field :image, class: "file" %>
              </div>
          </div>
            <div class="field">
              <div class="control">
                <%= f.submit "Upload an avatar", class: "button is-info"%>
              </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/find.html.erb
<div class="columns">
<div class="column">
  <%= render 'layouts/menu' %>
</div>
<div class="column is-half">

    <%= form_tag friends_new_path, method: "get" do %>
      <div class="field has-addons" style="margin-right: 20px; margin-top: 25px; margin-bottom: 20px;">
        <div class="control is-expanded">
          <%= text_field_tag :q, params[:q], class: "input", placeholder: "Find Someone"%>
        </div>
        <div class="control">
        <%= button_tag "Search", class: "button is-primary"%>
        </div>
      </div>
    <% end %>

  <% @users.each do |user| %>
    <% unless current_user.is_friend?(user) %>
    <div class="card" style="margin-right: 20px; margin-bottom: 20px; margin-top: 10px;">
        <div class="card-content is-clearfix">
            <div class="media-left is-pulled-left">
              <figure class="image is-96x96">
                <img src="<%= user.avatar %>" alt="Image" style="border-radius: 50%;">
              </figure>
            </div>
            <div class="media-content is-pulled-left">
              <p class="title is-4"><%= user.fullname %></p>
              <p class="subtitle is-6" style="margin-top: 2px;">Number of Friends: <%= user.friends.count%><br>
              Friended by: <%= Friendship.friended_by_count(user) %></p>
          </div>
            <%= form_for current_user.friendships.build(friend: user) do |f| %>
              <%= f.hidden_field :friend_id %>
              <%= button_tag "Add Friend", class: "button is-primary is-pulled-right" %>
            <% end %>
          </div>
         </div>
        <% end %>
      <% end %>
   </div>
   <div class="column">
  </div>
</div>

app/views/users/index.html.erb
<div class="columns">
<div class="column">
  <%= render 'layouts/menu' %>
</div>
<div class="column is-half">

  <%= form_tag users_path, method: "get" do %>
  <div class="field has-addons" style="margin-right: 20px; margin-top: 25px; margin-bottom: 20px;">
    
    <div class="control is-expanded">
      <%= text_field_tag :q, params[:q], class: "input", placeholder: "Find a Friend"%>
    </div>
    <div class="control">
    <%= button_tag "Search", class: "button is-info"%>
    </div>
  </div>
    <% end %>


  <% @users.each do |user| %>
    <% if current_user.is_friend?(user) %>
    <div class="card" style="margin-right: 20px; margin-bottom: 20px; margin-top: 10px;">
        <div class="card-content is-clearfix">
            <div class="media-left is-pulled-left">
              <figure class="image is-96x96">
                <img src="<%= user.avatar %>" alt="Image" style="border-radius: 50%;">
              </figure>
            </div>
            <div class="media-content is-pulled-left">
              <p class="title is-4">
                <%= link_to user.fullname, wall_path(id: user.id)%>
              </p>
              <p class="subtitle is-6" style="margin-top: 2px;">Number of Friends: <%= user.friends.count%><br>
              Friended by: <%= Friendship.friended_by_count(user) %></p>
          </div>
          
            <%= link_to icon("user-times", "Remove friend"), unfriend_path(friend_id: user.id), class: "button is-info is-pulled-right", method: :delete %>
          
          </div>
      </div>
    <% end %>
  <% end %>
   </div>
   <div class="column">
</div>
</div>

app/views/users/new.html.erb
<div class="columns">
  <div class="column is-one-third">

    <div class="card" style="margin-top: 25px;">
      <header class="card-header">
        <p class="card-header-title">
          Create a new account
        </p>
      </header>
      <div class="card-content">
      <%= form_for @user do |f| %>
        <div class="content">
          <div class="field">
            <div class="control">
              <%= f.text_field :firstname, placeholder: "First Name", class: "input"%>
            </div>
          </div>
          <div class="field">
              <div class="control">
              <%= f.text_field :lastname, placeholder: "Last Name", class: "input"%>
              </div>
          </div>
          <div class="field">
              <div class="control">
              <%= f.text_field :email, placeholder: "Email", class: "input"%>
              </div>
          </div>
          <div class="field">
              <div class="control">
              <%= f.file_field :avatar, class: "input"%>
              </div>
          </div>
          <div class="field">
              <div class="control">
              <%= f.password_field :password, placeholder: "Password", class: "input"%>
              </div>
          </div>
          <div class="field">
              <div class="control">
              <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "input"%>
              </div>
          </div>
            <div class="field">
              <div class="control">
                <%= f.submit "Sign Up", class: "button is-primary"%>
              </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="columns">
  <div class="column">
    <%= render 'layouts/menu' %>
  </div>
    <div class="column is-half">
      <%= render 'walls/profile_header.html.erb', user: @user %>
      <%= render 'wall_posts/wall_post_self_form', wallpost: @wallpost %>
      <div id="wall-posts">
        <%= render @wallposts %>
      </div>
      <div class="pagination hidden" id="pagination-loading" style="margin-top: 25px;" data-pagination-endpoint="<%= paging_wall_posts_path(source: "profile") %>" data-pagination-pages="<%= @wallposts.total_pages %>">
       <i class="fa fa-spinner fa-pulse fa-3x fa-fw" style="margin: auto"></i>
     </div>
    </div>
  <div class="column">
  </div>
</div>