config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users  do
    get :search, on: :collection, defaults: { format: 'json' }
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :friendships, only: [:new, :create, :destroy]
  resources :messages
  resources :wall_posts do
    get :paging, on: :collection
  end
  resources :comments

  post "logout" => "sessions#destroy"
  get "users" => "users#index"
  get "settings" => "users#edit"
  post "update" => "users#update"
  delete "unfriend" => "friendships#destroy"
  get 'inbox' => 'messages#inbox'
  get 'messages/new'
  get 'sent' => 'messages#sent'
  get 'friends/new' => "users#find"
  get 'profile' => 'users#show' 
  get 'newsfeed' => 'wall_posts#index'
  post "toggle_like" => "likes#toggle"
  get 'walls/:id' => 'walls#show', as: 'wall'
  get 'search/u' => 'home#searchu'
  get 'search/p' => 'home#searchp'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :skip_if_logged_in, only: [:index]

  def index
  end

  def searchu
    @users = User.where.not(id: current_user.id)
    
    if params[:q]
      search = params[:q]
      search = search.downcase
      @users = @users.select{|s| s.fullname.downcase.include?(params[:q])}
    end
  end

  def searchp
    @wall_posts = WallPost.all
    
    if params[:q]
      search = params[:q]
      search = search.downcase
      @wall_posts = @wall_posts.select{|s| s.body.downcase.include?(search)}
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_search_posts.html.erb
  <div class="card" style="margin-right: 20px; margin-bottom: 20px; margin-top: 10px;">
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <figure class="image is-48x48">
            <img src="<%= wall_post.author.avatar %>" alt="Image" style="border-radius: 50%;">
          </figure>
        </div>
        <div class="media-content">
          <% if wall_post.image.present? %>
            <%= image_tag wall_post.image, style: "margin-bottom: 10px;"%>
          <% end %>
          <p class="subtitle is-6"><%= wall_post.body %></p>
          <p style="font-style: italic; font-size: small">Posted by: 
            <%= link_to wall_post.author.fullname, wall_path(id: wall_post.author.id) %>
              <% unless wall_post.mention_id == nil %>
                on <%= link_to User.mentioned_name(wall_post), wall_path(id: wall_post.mention_id) %>'s Wall
              <% end %>
            <%= time_ago_in_words(wall_post.created_at) %> ago</p>
            <p style="font-style: italic; font-size: small"> 
            <% if wall_post.mentions.any? %>
              <%= display_mentions(wall_post) %>
            <% end %></p>
        </div>
      </div> 
    </div>
  </div>

app/views/home/_search_users.html.erb
  <div class="card" style="margin-right: 20px; margin-bottom: 20px; margin-top: 10px;">
    <div class="card-content is-clearfix">
        <div class="media-left is-pulled-left">
          <figure class="image is-96x96">
            <img src="<%= user.avatar %>" alt="Image" style="border-radius: 50%;">
          </figure>
        </div>
        <div class="media-content is-pulled-left">
          <p class="title is-4"><%= user.fullname %></p>
          <p class="subtitle is-6" style="margin-top: 2px;">Number of Friends: <%= user.friends.count%><br>
          Friended by: <%= Friendship.friended_by_count(user) %></p>
      </div>
      <% if current_user.is_friend?(user) %>
        <%= link_to icon("user-times", "Remove friend"), unfriend_path(friend_id: user.id), class: "button is-info is-pulled-right", method: :delete %>
      <% else %>
        <%= form_for current_user.friendships.build(friend: user) do |f| %>
          <%= f.hidden_field :friend_id %>
          <%= button_tag "Add Friend", class: "button is-primary is-pulled-right" %>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/home/index.html.erb
<div class="columns">
  <div class="column">
  </div>
  <div class="column is-half">

  <div class="card" style="margin-left: auto; margin-right: auto; margin-top: 100px;">
    <div class="card-content">
      <p class="title">
        Social networking app built using Rails and Bulma.
      </p>
    </div>
    <footer class="card-footer">
      <p class="card-footer-item">
        <span>
          Create an account <a href="<%= new_user_path %>">here</a>
        </span>
      </p>
      <p class="card-footer-item">
        <span>
          Log in <a href="<%= new_session_path %>">here</a>
        </span>
      </p>
    </footer>
  </div>
  </div>

  <div class="column">
  </div>
</div>

app/views/home/searchp.html.erb
<div class="columns">
    <div class="column">
      <%= render 'layouts/menu' %>
    </div>
    <div class="column is-half" style="margin-top: 25px;">
      <div class="tabs is-centered is-boxed is-medium">
        <ul>
          <li>
            <a href="<%= search_u_path(q: params[:q]) %>">
              <span class="icon is-small"><i class="fa fa-inbox"></i></span>
              <span>Users</span>
            </a>
          </li>
          <li class="is-active">
            <a href="<%= search_p_path(q: params[:q]) %>">
              <span class="icon is-small"><i class="fa fa-pencil"></i></span>
              <span>Posts</span>
            </a>
          </li>
        </ul>
      </div>
        <% @wall_posts.each do |wall_post| %>
          <%= render 'home/search_posts', wall_post: wall_post %>
        <% end %>
    </div>
    <div class="column">
    </div>
  </div>

app/views/home/searchu.html.erb
<div class="columns">
    <div class="column">
      <%= render 'layouts/menu' %>
    </div>
    <div class="column is-half" style="margin-top: 25px;">
      <div class="tabs is-centered is-boxed is-medium">
        <ul>
          <li class="is-active">
            <a href="<%= search_u_path(q: params[:q]) %>">
              <span class="icon is-small"><i class="fa fa-inbox"></i></span>
              <span>Users</span>
            </a>
          </li>
          <li>
            <a href="<%= search_p_path(q: params[:q]) %>">
              <span class="icon is-small"><i class="fa fa-pencil"></i></span>
              <span>Posts</span>
            </a>
          </li>
        </ul>
      </div>
        <% @users.each do |user| %>
          <%= render 'home/search_users', user: user %>
        <% end %>
    </div>
    <div class="column">
    </div>
  </div>