config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users  do
    get :search, on: :collection, defaults: { format: 'json' }
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :friendships, only: [:new, :create, :destroy]
  resources :messages
  resources :wall_posts do
    get :paging, on: :collection
  end
  resources :comments

  post "logout" => "sessions#destroy"
  get "users" => "users#index"
  get "settings" => "users#edit"
  post "update" => "users#update"
  delete "unfriend" => "friendships#destroy"
  get 'inbox' => 'messages#inbox'
  get 'messages/new'
  get 'sent' => 'messages#sent'
  get 'friends/new' => "users#find"
  get 'profile' => 'users#show' 
  get 'newsfeed' => 'wall_posts#index'
  post "toggle_like" => "likes#toggle"
  get 'walls/:id' => 'walls#show', as: 'wall'
  get 'search/u' => 'home#searchu'
  get 'search/p' => 'home#searchp'
end

app/models/wall_post.rb
class WallPost < ApplicationRecord
  belongs_to :author, class_name: "User"
  belongs_to :mentioned, class_name: "User", optional: true
  validates :body, presence: true
  has_many :likes, as: :item
  has_many :comments
  has_many :mentions
  mount_uploader :image, ImageUploader

  def display_comments_count
    if comments.count == 0
      "No Comments Yet"
    elsif comments.count == 1
      "1 Comment"
    else
      "#{comments.count} Comments"
    end
  end

  def self.generate_posts(n = 5, user = nil)
    user ||= User.last
    n.times do 
      wall_post = WallPost.create(body: Faker::HowIMetYourMother.quote,
        mention_id: 51,
        author: User.random_user
      )
      rand(3).times do
        wall_post.comments.create(
          body: Faker::HowIMetYourMother.catch_phrase,
          user: User.random_user
        )
      end
      rand(5).times do
        wall_post.mentions.create(
          user: User.random_user
        )
      end
    end
  end
end

app/controllers/wall_posts_controller.rb
class WallPostsController < ApplicationController
  before_action :require_login

  def create
    wallpost = current_user.wall_posts.create(wall_post_params)
    if params[:wall_post][:mention_id].present?
      wallpost.save
      #WallPostMailer.new_post(wallpost).deliver_now
      #NotifySlack.new.notify_new_wall_post(wallpost)
      flash[:success] = "Posted!"
      redirect_back fallback_location: newsfeed_path
    elsif wallpost.save
      #NotifySlack.new.notify_new_wall_post(wallpost)
      flash[:success] = "Posted!"
      redirect_back fallback_location: newsfeed_path
    else
      flash[:error] = "Something went wrong. Please try again."
      redirect_to fallback_location: newsfeed_path
    end

    if params[:mentions].present?
      mentions = params[:mentions].split(',')
      mentions.shift
      mentions.each do |mention|
        wallpost.mentions.create(user_id: mention)
      end
    end
  end

  def index
    @user = current_user
    #@wallposts = WallPost.all.sort_by(&:created_at).reverse
    @wallposts = WallPost.order("updated_at DESC").page(1).per(5)
    @wallpost = WallPost.new
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @wallpost = WallPost.find(params[:id])

    respond_to do |format|
      format.html
      format.json
    end
  end

  def paging
    params[:per] ||= 5

    if params[:source] == "newsfeed"
      @wallposts = WallPost.order("updated_at DESC").page(params[:page]).per(params[:per])
    elsif params[:source] == "profile"
      @wallposts = current_user.posts_on_wall(current_user).order("updated_at DESC").page(params[:page]).per(params[:per])
    else params[:source] == "wall"
      @user = User.find(params[:id])
      @wallposts = @user.posts_on_wall(@user).order("updated_at DESC").page(params[:page]).per(params[:per])
    end

    render partial: 'wall_post', collection: @wallposts, layout: false
  end

  private

  def wall_post_params
    params.require(:wall_post).permit(:body, :mention_id, :image)
  end
  
end

app/helpers/wall_posts_helper.rb
module WallPostsHelper

  def display_mentions(wall_post)
    if wall_post.mentions.count  == 1
      "With " + wall_post.mentions.first.user.fullname
    elsif wall_post.mentions.count  == 2
      "With " + wall_post.mentions.first.user.fullname + " and 1 other"
    else
      "With " + wall_post.mentions.first.user.fullname + " and #{wall_post.mentions.count-1} others"
    end
  end
end

app/views/wall_posts/_card_comment_form.html.erb
<div class="card comment-form <%= 'hidden' if wall_post.comments.empty? %>">
  <div class="card-content" id="wall_post">
    
    <div class="media">
      <div class="media-left">
        <figure class="image is-24x24">
          <img src="<%= current_user.avatar %>" alt="Image" style="border-radius: 50%;">
        </figure>
      </div>

      <div class="media-content">
        <%= form_for comment, remote: true do |f| %>
          <div class="field">
            <div class="control">
              <%= f.hidden_field :wall_post_id, value: wall_post.id %>
              <%= f.text_area :body, class: "textarea js-new-comment", rows: "1"%>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <button class="button is-primary">Post
              </button>
            </div>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/wall_posts/_card_comments.html.erb
<div class="card comment-display <%= 'hidden' if wall_post.comments.empty? %>">
  <div class="card-content" id="wall_post">
      <div class="comments">
        <% if wall_post.comments.empty? %>
          <div class="no-comments">
            No comments yet. Be the first to comment!
          </div>
        <% else %>
          <%= render wall_post.comments %>
        <% end %>
      </div>
  </div>
</div>

app/views/wall_posts/_card_content.html.erb
<div class="card-content">
  <div class="media">
    <div class="media-left">
      <figure class="image is-48x48">
        <img src="<%= wall_post.author.avatar %>" alt="Image" style="border-radius: 50%;">
      </figure>
    </div>
    <div class="media-content">
      <% if wall_post.image.present? %>
        <%= image_tag wall_post.image, style: "margin-bottom: 10px;"%>
      <% end %>
      <p class="subtitle is-6"><%= wall_post.body %></p>
      <p style="font-style: italic; font-size: small">Posted by: 
        <%= link_to wall_post.author.fullname, wall_path(id: wall_post.author.id) %>
          <% unless wall_post.mention_id == nil %>
            on <%= link_to User.mentioned_name(wall_post), wall_path(id: wall_post.mention_id) %>'s Wall
          <% end %>
        <%= time_ago_in_words(wall_post.created_at) %> ago</p>
        <p style="font-style: italic; font-size: small"> 
        <% if wall_post.mentions.any? %>
          <%= display_mentions(wall_post) %>
        <% end %></p>
    </div>
  </div> 
</div>

  <%= render "wall_posts/likes_sentence", wall_post: wall_post %> 

<div class="card-footer">
  <div class="level">
    <div class="level-left">
      <div class="level-item">
        <%= link_to fa_icon("thumbs-up", text: "Like"), toggle_like_path(wall_post_id: wall_post.id), 
            class: "button is-white js-like-button #{"is-liked" if current_user.likes.where(item: wall_post.id).first}", 
            method: "post", remote: true %>
      </div>
      <div class="level-item">
        <%= link_to fa_icon("comments", text: "#{wall_post.display_comments_count}"), "#", class: "button is-white #{"is-liked" if wall_post.comments.count > 0} comment-toggle"%>
      </div>
    </div>
  </div>
</div>

app/views/wall_posts/_likes_sentence.html.erb
 <div class="card-footer likes-sentence">
  <% if wall_post.likes.count > 0 %>
    <p class="card-footer-item">
      <%= fa_icon("thumbs-up", text: "") %>
      <small style="font-style: italic;">
        <%= wall_post.likes.map {|l| l.user.fullname}.to_sentence %>
      </small>
    </p>
  <% end %>
</div>

app/views/wall_posts/_wall_post.html.erb
<div class="wall_post-content">
  <div class="card" style="margin-top: 25px;" id="<%= dom_id wall_post %>">
    <%= render 'wall_posts/card_content', wall_post: wall_post %>
    <%= render 'wall_posts/card_comments', wall_post: wall_post %>
    <%= render 'wall_posts/card_comment_form', wall_post: wall_post, comment: Comment.new %>
  </div>
</div>

app/views/wall_posts/_wall_post_self_form.html.erb
<div class="card" style="margin-top: 25px;">
  <div class="card-content" id="wallpost"> 
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="<%= current_user.avatar %>" alt="Image" style="border-radius: 50%;">
        </figure>
      </div>
      <div class="media-content">
        <%= form_for wallpost do |f| %>
          <div class="field">
            <div class="control">
              <%= f.text_area :body, class: "textarea "%>
            </div>
          </div>

            <div class="field">
              <%= f.label :mentions, "Find users to mention:", class: "label", id: "" %>
                <div id="data-holder-selected" style="margin-bottom: 10px;">
                </div>
                <div class="control">
                  <%= text_field_tag :q, params[:q], class: "input", placeholder: "Find users...", id: "provider-remote" %>
                  <%= hidden_field_tag "mentions", "", id: "data-holder" %>
                </div>
            </div>

          <div class="field">
          <%= f.label :image, "Upload an image", class: "label" %>
            <div class="control">
              <%= f.file_field :image, class: "file" %>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <button class="button is-primary">Post
              </button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>  
</div>

app/views/wall_posts/index.html.erb
<div class="columns">
  <div class="column">
    <%= render 'layouts/menu' %>
  </div>  
  <div class="column is-half">
    <div id="wall-posts">
      <%= render 'wall_post_self_form', wallpost: @wallpost %>
      <%= render @wallposts %>
    </div>
    <div class="pagination hidden" id="pagination-loading" style="margin-top: 25px;" data-pagination-endpoint="<%= paging_wall_posts_path(source: "newsfeed") %>" data-pagination-pages="<%= @wallposts.total_pages %>">
      <i class="fa fa-spinner fa-pulse fa-3x fa-fw" style="margin: auto"></i>
    </div>
  </div>
  <div class="column">
  </div>
</div>