config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users  do
    get :search, on: :collection, defaults: { format: 'json' }
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :friendships, only: [:new, :create, :destroy]
  resources :messages
  resources :wall_posts do
    get :paging, on: :collection
  end
  resources :comments

  post "logout" => "sessions#destroy"
  get "users" => "users#index"
  get "settings" => "users#edit"
  post "update" => "users#update"
  delete "unfriend" => "friendships#destroy"
  get 'inbox' => 'messages#inbox'
  get 'messages/new'
  get 'sent' => 'messages#sent'
  get 'friends/new' => "users#find"
  get 'profile' => 'users#show' 
  get 'newsfeed' => 'wall_posts#index'
  post "toggle_like" => "likes#toggle"
  get 'walls/:id' => 'walls#show', as: 'wall'
  get 'search/u' => 'home#searchu'
  get 'search/p' => 'home#searchp'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :wall_post
  validates :body, presence: true
  has_many :likes, as: :item
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"

  def self.friended_by_count(user)
    Friendship.where(friend: user).count
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item, polymorphic: true
end

app/models/mention.rb
class Mention < ApplicationRecord
  belongs_to :user
  belongs_to :wall_post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
  validates :body, presence: true
end

app/models/notify_slack.rb
class NotifySlack < ApplicationRecord
  def initialize
    @notifier = Slack::Notifier.new ENV["SLACK_WEBHOOK_URL"]
  end

  def notify_new_wall_post(post)
    @notifier.ping(post.body,
      username: post.author.fullname,
      icon_url: post.author.avatar.url,
      attachments: [image_url: post.image.url, title: post.body]
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :firstname, presence: true, length: { in: 2..20 }
  validates :lastname, presence: true, length: { in: 2..20 }
  validates :email, presence: true, uniqueness: true
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, dependent: :destroy
  has_many :received_messages, foreign_key: "recipient_id", class_name: "Message", dependent: :destroy
  has_many :sent_messages, foreign_key: "sender_id", class_name: "Message", dependent: :destroy
  has_many :wall_posts, foreign_key: "author_id", class_name: "WallPost", dependent: :destroy
  has_many :wall_mentions, foreign_key: "mention_id", class_name: "WallPost", dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :walls,  dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  
  #validates_email_format_of :email, :message => "needs to be a valid email address."
  has_secure_password

  def image_url_or_default
    avatar.url || image_url.presence || "http://lorempixel.com/128/128/people/Fake-User/"
  end

  def self.generate_users(n = 25, gender = "female")
    url = "https://randomuser.me/api?results=#{n}&gender=#{gender}"
    body = HTTP.get(url).parse
    body["results"].each do |person|
      hash = {}
      hash[:firstname] = person["name"]["first"]
      hash[:lastname] = person["name"]["last"]
      hash[:email] = person["email"]
      hash[:password] = person["login"]["password"]
      hash[:remote_avatar_url] = person["picture"]["large"]
      User.create! hash
    end
  end

  def add_friend(friend)
    friends << friend
  end

  def is_friend?(friend)
    friends.include?(friend)
  end

  def added_as_friend_count(user)
    added_list = friendships.find_by(friend_id: user.id)
    added_list.count
  end

  def recipients
    friends.map{|e| [e.fullname, e.id]}
  end

  def fullname
    fullname = firstname.titleize + " " + lastname.titleize
    fullname
  end

  def self.mentioned_name(wall_post)
    user = User.find(wall_post.mention_id)
    user.fullname
  end

  def likes_toggle!(item)
    likes.where(item: item).first ? likes.where(item: item).first.destroy : likes.create(item: item)
  end

  def self.random_user
    random_index = rand(User.count)
    User.offset(random_index).first
  end

  def posts_on_wall(user)
    WallPost.where(mention_id: user.id).or(WallPost.where(author: user))
  end

  def self.autocomplete_by_name(q)
    User.where('firstname ILIKE ?', "%#{q}%")
  end
end

app/models/wall_post.rb
class WallPost < ApplicationRecord
  belongs_to :author, class_name: "User"
  belongs_to :mentioned, class_name: "User", optional: true
  validates :body, presence: true
  has_many :likes, as: :item
  has_many :comments
  has_many :mentions
  mount_uploader :image, ImageUploader

  def display_comments_count
    if comments.count == 0
      "No Comments Yet"
    elsif comments.count == 1
      "1 Comment"
    else
      "#{comments.count} Comments"
    end
  end

  def self.generate_posts(n = 5, user = nil)
    user ||= User.last
    n.times do 
      wall_post = WallPost.create(body: Faker::HowIMetYourMother.quote,
        mention_id: 51,
        author: User.random_user
      )
      rand(3).times do
        wall_post.comments.create(
          body: Faker::HowIMetYourMother.catch_phrase,
          user: User.random_user
        )
      end
      rand(5).times do
        wall_post.mentions.create(
          user: User.random_user
        )
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :skip_if_logged_in, only: [:index]

  def index
  end

  def searchu
    @users = User.where.not(id: current_user.id)
    
    if params[:q]
      search = params[:q]
      search = search.downcase
      @users = @users.select{|s| s.fullname.downcase.include?(params[:q])}
    end
  end

  def searchp
    @wall_posts = WallPost.all
    
    if params[:q]
      search = params[:q]
      search = search.downcase
      @wall_posts = @wall_posts.select{|s| s.body.downcase.include?(search)}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def icon(icon_name, text)
    content_tag(:span, fa_icon(icon_name), class: "icon") + content_tag(:span, text)
  end

  def class_for flash_type
    { success: 'is-primary', error: 'is-danger', notice: 'is-warning'}[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.map do |msg_type, message|
      content_tag(:div, class: "message #{class_for(msg_type)}") do
        content_tag(:div, class: "message-body") do
          (message).html_safe
        end
      end
    end.join.html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wall_posts_helper.rb
module WallPostsHelper

  def display_mentions(wall_post)
    if wall_post.mentions.count  == 1
      "With " + wall_post.mentions.first.user.fullname
    elsif wall_post.mentions.count  == 2
      "With " + wall_post.mentions.first.user.fullname + " and 1 other"
    else
      "With " + wall_post.mentions.first.user.fullname + " and #{wall_post.mentions.count-1} others"
    end
  end
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/layouts/_menu.html.erb
<aside class="menu" style="margin-top: 25px;">
  <p class="menu-label">
    <%= current_user.fullname %>
  </p>
  <ul class="menu-list">
    
    <li><%= link_to icon("list-alt", "Newsfeed"), newsfeed_path, class: "#{'is-active' if current_page?(newsfeed_path)}" %></li>
    <li><%= link_to icon("user", "Profile"), profile_path, class: "#{'is-active' if current_page?(profile_path)}"  %></li>
    <li><%= link_to icon("cog", "Settings"), settings_path, class: "#{'is-active' if current_page?(settings_path)}"  %></li>
  </ul>
  <p class="menu-label">
    Messaging
  </p>
  <ul class="menu-list">
    <li><%= link_to icon("envelope", "Inbox"), inbox_path, class: "#{'is-active' if current_page?(inbox_path)}"  %></li>
    <li><%= link_to icon("pencil", "New"), messages_new_path, class: "#{'is-active' if current_page?(messages_new_path)}"  %></li>
    <li><%= link_to icon("send", "Sent"), sent_path, class: "#{'is-active' if current_page?(sent_path)}"  %></li>
  </ul>
  <p class="menu-label">
    Friends
  </p>
  <ul class="menu-list">
    <li><%= link_to icon("users", "Friend List"), users_path, class: "#{'is-active' if current_page?(users_path)}"  %></li>
    <li><%= link_to icon("search", "Find Friends"), friends_new_path, class: "#{'is-active' if current_page?(friends_new_path)}"  %></li>
  </ul>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DuckSocial</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <nav class="navbar ">
      <div class="navbar-brand">
        <a href="<%= root_path %>" class="navbar-item">
          <%= image_tag "duck_min.png" %>
          <strong style="margin-left: 5px;">DuckSocial</strong>
          </a>
      </div>
      <% if current_user %>
      
        <div class="navbar-item">
          <%= form_tag search_u_path, method: "get" do %>
            <div class="field has-addons">
              <div class="control">
                <%= text_field_tag :q, params[:q], class: "input", placeholder: "Search..." %>
              </div>
              <div class="control">
                <%= button_tag "Search", class: "button is-primary"%>
              </div>
            </div>
          <% end %>
        </div>

      <div class="navbar-end">
        <%= link_to icon("sign-out", "Sign Out"), logout_path, class: "navbar-item", method: :post  %>
      </div>
      <% else %>
      <div class="navbar-brand">
        <%= link_to icon("user-plus", "Sign Up"), new_user_path, class: "navbar-item"  %>
      </div>
      <div class="navbar-brand">
        <%= link_to icon("sign-in", "Sign In"), new_session_path, class: "navbar-item"  %>
      </div>
      <% end %>
    </nav>
    <%= flash_messages %>
    <div class="container is-fluid">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
  </body>
</html>

app/views/layouts/messages.html.erb
<% content_for(:content) do %>
  <div class="columns">
    <div class="column">
      <%= render 'layouts/menu' %>
    </div>
    <div class="column is-half" style="margin-top: 25px;">
      <div class="tabs is-centered is-boxed is-medium">
        <ul>
          <li class="<%= 'is-active' if current_page?(inbox_path) %>">
            <a href="<%= inbox_path %>">
              <span class="icon is-small"><i class="fa fa-inbox"></i></span>
              <span>Inbox</span>
            </a>
          </li>
          <li class="<%= 'is-active' if current_page?(messages_new_path) %>">
            <a href="<%= messages_new_path %>">
              <span class="icon is-small"><i class="fa fa-pencil"></i></span>
              <span>New</span>
            </a>
          </li>
          <li class="<%= 'is-active' if current_page?(sent_path) %>">
            <a href="<%= sent_path %>">
              <span class="icon is-small"><i class="fa fa-send"></i></span>
              <span>Sent</span>
            </a>
          </li>
        </ul>
      </div>
      <%= yield %>
    </div>
    <div class="column">
    </div>
  </div>
<% end %>

<%= render file: "layouts/application" %>